### ISSUE TITLE
My 2 cents on the structure

### ISSUE THREAD

**Issue by yamin8000** [ManiMozaffar/awesome-resumes#3]
> A good photo is better than no photo, and no photo is better than bad photo. Good photo is considered as you wearing a professional clothes, such as suit.

Why? Does wearing a suit make you a better programmer? I understand that in an office wearing appropriate clothes is professional behavior but I don't understand how adding a picture to a resume makes it somehow better. If someone is hiring based on quality or existence or lack of a picture on a resume I don't take their other criteria to be proficient.

> Make sure your jobs don't have overlap with each other or other experiences, such as teaching, only overlap that is allowed is Work Experience with Education.

I understand that overlapping two full-time jobs on a resume is relatively questionable, but not every time that's correct. Occasionally people really have two jobs at the same time, one full-time and another part-time or two part-time. Even someone can be a full-time employee at a company but consult multiple people or companies simultaneously. I don't think this is the right restriction for a resume structure.

> Templates

Maybe I'm opinionated but over the years I came to the conclusion that templates limit your potential to create a customized personal resume. If one wants to use a template it's better to use LaTeX or even better to write a resume entirely yourself with LaTeX as it's one of the best standards for creating documents in the scientific/engineering or even software industry rather than using weak WYSIWYG word processors.

**Comment by ManiMozaffar** [comment]
Hey mate,
yes generally Latex is a good option, but not everyone knows latex. people who do, knows that they can use it, but i'll add it to templates. A good picture isn't a must, that's how I said it, a good picture always put positive remark on the HR, it has to do with psychology , and it's pretty fine if you don't include it, because it shouldn't matter for them in an ideal status.
Speaking for myself, I've been rejected few time just because of overlaps in my CV, which one was part time and one full time, so it's not ideal to work 2 jobs at same time, it's better for them that you focus on one, that is what they want when they attempt to visa sponsership you.
